from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# ----------- Backbone ----------- #
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.BACKBONE.FREEZE_AT = 3

# ------------- RPN -------------- #
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

# ------------- ROI -------------- #
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7  # for faster
# _CC.MODEL.ROI_HEADS.EMA_MOMENTUM = 0.92
# _CC.MODEL.ROI_HEADS.MARGIN_GAMMA = 0.15
# _CC.MODEL.ROI_HEADS.MARGIN_TOPK = 2
# _CC.MODEL.ROI_HEADS.MARGIN_SCALE = 0.25
# _CC.MODEL.ROI_HEADS.MARGIN_REDUCTION = "mean"

# ------------- TEST ------------- #
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = 'resnet'             # res-like
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05

# ------------ Other ------------- #
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True

_CC.MODEL.REFINE = CN()
_CC.MODEL.REFINE.MOMENTUM = 0.5
_CC.MODEL.REFINE.NUM_CLASSES = 24  # 默认值，可被 yaml 覆盖
_CC.MODEL.REFINE.WARMUP_ITERS = 0
_CC.MODEL.REFINE.EPS = 1e-12